### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by jnormington** [geckoboard/everdeen#16]
- [ ] Update the hash access in this ruby client with @boxofrad helper suggestion https://github.com/geckoboard/everdeen/pull/15 so we don't have to include ActiveSupport gem... phew!
- [ ] Update everdeen server for each request to have an id in the request struct.
- [ ] Update ruby client to include and process that new id
- [ ] Update the ruby client to request overridden `==` method to check against the id instead
- [ ] Better way of handling the pid stuff ?
- [ ] Spec helper bulk out with random specs ;)
